// Generated by CoffeeScript 1.7.1
define(['jquery'], function($j) {
  var getFileViewerElement;
  getFileViewerElement = function() {
    return $j('#file-viewer');
  };
  return {
    getFileViewerElement: getFileViewerElement
  };
});

//# sourceMappingURL=file_viewer_utils.map
